version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: traceandmoment
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
